name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t boombox .
  deploy:
    name: Push Docker image
    needs: [build]
    runs-on: [self-hosted]
    steps:
      - name: Push to registry
        run: |
          docker tag boombox procrastination-team:5000/boombox:${GITHUB_REF##*/}-${{ github.sha }} && \
          docker push procrastination-team:5000/boombox:${GITHUB_REF##*/}-${{ github.sha }}
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag procrastination-team:5000/boombox:${GITHUB_REF##*/}-${{ github.sha }} procrastination-team:5000/boombox:latest && \
          cd /srv/boombox/backend && \
          docker-compose up
