name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [self-hosted, build]
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t registry.procrastination-team.com/boombox:${GITHUB_REF##*/}-${{ github.sha }} .
      - name: Push to registry
        run: docker push registry.procrastination-team.com/boombox:${GITHUB_REF##*/}-${{ github.sha }}
  deploy:
    name: Deploy
    needs: [build]
    runs-on: [self-hosted, deploy]
    steps:
      - name: Deploy
        run: |
          docker pull registry.procrastination-team.com/boombox:${GITHUB_REF##*/}-${{ github.sha }} && \
          docker tag registry.procrastination-team.com/boombox:${GITHUB_REF##*/}-${{ github.sha }} boombox:latest && \
          docker rmi registry:5000/boombox:${GITHUB_REF##*/}-${{ github.sha }} && \
          cd /srv/boombox/backend && \
          docker-compose up -d
